name: Deploy Medical Assistant

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    
    - name: 'Deploy to Cloud Run'
      run: |
        cd backend
        gcloud run deploy nuvaface-medical-assistant \
          --source=. \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --memory=4Gi \
          --cpu=2 \
          --port=8080